application: food-rescue
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /scripts
  static_dir: scripts

- url: /admin/.*
  script: controllers.admin.app

- url: /donor/*
  script: controllers.donor.app

- url: /*
  script: controllers.main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
