application: food-rescue
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static_assets
  static_dir: static_assets

- url: /admin/*
  script: controllers.admin.app
  login: admin

- url: /endpoints/*
  script: controllers.main.endpoints

- url: /*
  script: controllers.main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
